### ISSUE TITLE
What do I need to know after change crop size to 96? 

### ISSUE THREAD

**Issue by boshuru** [vuptran/cardiac-segmentation#4]
Hello, if I change the crop size from 100 to 96 in train_sunnybrook.py, fcn_model.py, and submist_sunnybrook.py, will it cause any problem? I can get the codes working well, so the question is not about if there would be execution error. I am not sure if you guys choose crop size of 100 for some reasons specific to this Sunnybrook image data?

**Comment by vuptran** [comment]
`crop_size = 100` was a data-driven decision because it captures all of the left ventricle in the Sunnybrook dataset. If you choose a smaller `crop_size`, there are two things to consider:
1. Need to make sure `ZeroPadding2D` in `fcn_model.py` has sufficient padding after pooling and subsampling;
2. There will be missing pixels for the left ventricle at the edges.
